- name: Get the list of virtual machines in the directory
  community.vmware.vmware_vm_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: false
    folder: "{{ folder }}"
  register: vm_info

- name: Get VM Snapshot Facts
  community.vmware.vmware_guest_snapshot_info:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    folder: "{{ folder }}"
    name: "{{ item.guest_name }}"
  register: snapshot_info
  loop: "{{ vm_info.virtual_machines }}"
  delegate_to: localhost

- name: Print snapshot info
  debug:
    var: snapshot_info.results

- name: Restore Latest Snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    folder: "{{ folder }}"
    name: "{{ item.item.guest_name }}"
    state: revert
    snapshot_name: "{{ item.guest_snapshots.current_snapshot.name }}"
  delegate_to: localhost
  loop: "{{ snapshot_info.results }}"

- name: Power On VMs
  community.vmware.vmware_guest_powerstate:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    name: "{{ item.guest_name }}"
    state: powered-on
  loop: "{{ vm_info.virtual_machines }}"
  delegate_to: localhost
