- name: Get VM Snapshot Facts
  community.vmware.vmware_guest_snapshot_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
  register: snapshot_info
  delegate_to: localhost

- name: Restore Latest Snapshot
  community.vmware.vmware_guest_snapshot:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    datacenter: "{{ datacenter_name }}"
    name: "{{ vm_name }}"
    state: revert
    snapshot_name: "{{ snapshot_info.snapshot_list | last }}"
  delegate_to: localhost

